spring.application.name = DemoProject

# TomCat WebServer Configuration
server.port=8800

# Active profile in MySql DataBase
spring.profiles.active=Mysql

# Spring Security Configuration
spring.jwtToken.secretKey = 4461ada8eb99c9a3ee5162d10f42152117fc92bac295868b8b2c4e927ba741b8

# Logging Configuration
#logging.level.root = DEBUG
#spring.output.ansi.enabled = ALWAYS

